name: Lint Check

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "<python_version>" # e.g. 3.11
          auto-update-conda: true
          environment-file: environment.yml # Update this path to your actual environment.yml location
          activate-environment: <env_name>_env

      - name: Verify Conda environment
        run: conda info --envs

      - name: Run backend linting
        run: |
          eval "$(conda shell.bash hook)"
          conda activate <env_name>_env
          make lint
